{% set version = "1.0.0" %}

package:
  name: norse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/norse/norse-{{ version }}.tar.gz
  sha256: 92f6bd0d97aa519ffcb605a25c4bda1ef1d949de8f87d0450eb1176ee7de69c9

build:
  number: 4
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]
  rpaths:
    - lib/
    - {{ SP_DIR }}/torch/lib

requirements:
  build:
    - pytorch                                # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 ==2.17                # [linux64]
    - cmake
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - pip
    - python
    - pytorch
  run:
    - python
    - numpy
    - torchvision >=0.10.0

test:
  imports:
    - norse

about:
  home: http://github.com/norse/norse
  summary: A library for deep learning with spiking neural networks
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
