{% set version = "1.1.0" %}

package:
  name: norse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/norse/norse-{{ version }}.tar.gz
  sha256: 3f70b8579251316761f7a950680136029fcd9d92bbcc53531366d088a8aaf0c8
  patches:
    - fix-pytree.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]
  rpaths:
    - lib/
    - {{ SP_DIR }}/torch/lib

requirements:
  build:
    - pytorch                                # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 ==2.17                # [linux64]
    - cmake
    - make
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - pip
    - python
    - pytorch
  run:
    - python
    - numpy
    - pytorch
    - torchvision >=0.10.0
    - nir
    - bindsnet  # [py<310]
    - matplotlib-base
    - pytorch-lightning
    - pandas
    - nirtorch
    - h5py

test:
  imports:
    - norse

about:
  home: http://github.com/norse/norse
  summary: A library for deep learning with spiking neural networks
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
